name: Integración Continua (CI)
on:
  push:
    branches: [ main ]
jobs:
  build_and_test :
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
        node:version: ['18', '20']
    steps:    
      - name: 1. Descargar Código
        uses: actions/checkout@v4
      - name: 2. Configurar Node.js($((matrix.node-version)))  
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 3. Instalar Dependencias
        run: npm ci
      - name: 4. probar el codigo
        run: npm test
  deploy:
    needs: [build_and_test]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 1. descargar el cosdigo
        uses: actions/checkout@v4
      - name: 2. despliegue
        run: echo "despliegue exitoso"
    
        
        
        
